# 2019-01-16 (cc) <paul4hough@gmail.com>
#
---
global:
  scan_freq: 30m

log-files:
  - name: log_httpd_error # alertmanger alert name
    file: /var/http/error.log
    regex:
      - error/i
    annotations:
      sop: http://wiki/sop-log_httpd_error
      match_lines: "{{ $match.lines }}"
      match_first: "{{ $match.lnum_first }}"
      match_last: "{{ $match.lnum_last }}"
      match_range: "{{ $match.lnum_range }}"

  - name: log_httpd_access
    file: "/var/http/access.{{ $date }}.log"
    regex:
      - status=[3-5]\d\d

  - name: log_messages
    file: /var/log/messages
    regex:
      - error/i


alertmanagers:
  - scheme: https
    static_configs:
      - targets:
        - "1.2.3.4:9093"
        - "1.2.3.5:9093"
        - "1.2.3.6:9093"
